config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts do
    member do
      post '/create_comment' => 'posts#create_comment', as: 'create_comment_to'
      post '/like_post' => 'posts#like_post', as: 'like_to'
    end
    collection do
      delete '/:comment_id/destroy_comment'  => 'posts#destroy_comment', as: 'destroy_comment'
      get '/page_scroll' => 'posts#page_scroll', as: 'scroll'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    
    def self.MAX_LENGTH
         40 
    end
    
    
  belongs_to :post
  validates :body, length: {maximum: self.MAX_LENGTH},
                    presence: true
                    

  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    has_many :likes
    paginates_per 40
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :create_comment, :like_post]
  before_action :is_login?, only: [:create_comment, :like_post, :destroy_comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @like = true
    if user_signed_in?
      @like = current_user.likes.find_by(post_id: @post.id).nil?
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_comment
    # puts params[:body]
   
    @c = @post.comments.create(comment_params) # 와일드카드를 쓰고 있으므로 id도 같이 넘어온다. 
  end
  
  def like_post
    # puts "Like Post Success"
    unless user_signed_in?
      respond_to do |format|
        format.js {render 'please_login.js.erb'}
      end
    else
      if Like.where(user_id: current_user.id, post_id: @post.id).first.nil?
        # 좋아요 누르지 않은 상태에 대한 실행문
        # 좋아요를 만들어준다.
        @result = current_user.likes.create(post_id: @post.id)
        # puts "좋아요 누름"
      else 
        # 좋아요를 누른 상태에 대한 실행문
        # 기존의 좋아요를 삭제한다. 
        
        @result = current_user.likes.find_by(post_id: @post.id).destroy
        # puts "좋아요 취소"    
      end
      # puts ("test가 나오나 안나오나")
      @result = @result.frozen?
      puts @result
    end
  end
  
  
  def destroy_comment
    @c = Comment.find(params[:comment_id]).destroy
    puts @c.body
  end
  
  
  def page_scroll
      @posts = Post.order("created_at DESC ").page(params[:page])
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def is_login?
      unless user_signed_in?
        respond_to do |format|
          format.js {render 'please_login.js.erb'}
        end
      end
    end
    
    
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
    
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if user_signed_in? %>
    <%=link_to "SIGN OUT", destroy_user_session_path, method: :delete, data: {confirm: "로그아웃 하시겠습니까?"}%>
  <% else %>
    <%=link_to "SIGN IN", new_user_session_path, data: {confirm: "로그인 하시겠습니까?"}%>
  <% end %>
  <%=link_to "HOME", root_path %>
  <br>
  <br>
  <%= link_to 'New Post', new_post_path, class: "btn btn-warning" %>
  
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/create_comment.js.erb
alert("댓글이 등록됨");
$('#comment_body').val("");
$('#comment_table tbody').prepend(
`<tr id="<%= "comment-#{@c.id}" %>">
    <td><%= @c.body%></td>
    <td><%=link_to "삭제", destroy_comment_posts_path(@c.id), method: :delete, data: {confirm: "삭제하시겠습니까?"}, class: "btn btn-warning", remote: true%></td>
</tr>`);

app/views/posts/destroy_comment.js.erb
$('#comment-<%= @c.id %>').fadeOut().remove;

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table" id="myTable">
  <thead>
    <tr>
      <th>No.</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= truncate post.content, length: 10 %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= paginate @posts %>

<script>
$(function() {
  var page_scroll_index = 2;
    $(document).on('scroll', function() {
      // console.log("움직인다다다다다");
      //var end =
      if($(window).scrollTop() >= $(document).height() - $(window).height()){
        // console.log(end);
        $.ajax({
          method: "GET",
          url: "<%= scroll_posts_path %>",
          data: {
            page: page_scroll_index++
          }
        });
      }
    });
}); 
</script>

app/views/posts/like_post.js.erb
if(<%= @result %>) {
    $('#like_button').text("Like").addClass("btn-info").removeClass("btn-danger");
}
else{
    $('#like_button').text("Dislike").addClass("btn-danger").removeClass("btn-info");
}
console.log("done");
$('#like_count').text(<%=@post.likes.count%>);

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/page_scroll.js.erb
alert("스크롤 무한스크롤 ㅋㅋㅋ");

     $('#myTable tbody').append(
     `
     <% @posts.each do |post| %>
     <tr>
         <td><%= post.id %></td>
         <td><%= post.title %></td>
         <td><%= truncate post.content, length: 10 %></td>
         <td><%= link_to 'Show', post %></td>
         <td><%= link_to 'Edit', edit_post_path(post) %></td>
         <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
     <% end %>
     `);   

app/views/posts/please_login.js.erb
if(confirm("로그인이 필요합니다. \n 로그인 페이졸 이동하시겠습니까?"))
location.href = "<%=new_user_session_path%>"

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>


<%=form_tag create_comment_to_post_path, id: "comment" do%>
  <%=text_field_tag "comment[body]"%>
  <%=submit_tag "댓글달기"%>
<% end %>
<h3><span id="word_count">0</span><%= Comment.MAX_LENGTH%></h3>


<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %>
<%= link_to 'Back', posts_path, class: "btn btn-success" %>

<% if @like %>
  <%=link_to "Like", like_to_post_path, class: "btn btn-info", id: "like_button" %>
<% else %>
  <%=link_to "DisLike", like_to_post_path, class: "btn btn-danger", id: "like_button" %>
<% end %>

<span id='like_count'><%=@post.likes.count%></span>

<table class="table", id="comment_table">
  <thead>
      <tr>
        <th class="text-center" width='90%'>댓글</th>
        <th with="10%"></th>
      </tr>
  </thead>
  <tbody>
    <% @post.comments.reverse.each do |p|%>
      <tr id="comment-<%= p.id %>">
          <td><%= p.body %></td>
          <td><%=link_to "삭제", destroy_comment_posts_path(p.id), method: :delete, data: {confirm: "삭제하시겠습니까?"}, class: "btn btn-warning", remote: true%></td>
      </tr>
    <% end %>
  </tbody>  
</table>
  

<script>

  $(function() {
    $('#like_button').on('click', function(e) {
      e.preventDefault();
      console.log("Like Button Clicked");
      $.ajax({
        method: "POST",
        url: "<%= like_to_post_path %>"
      })
    })
    
    
    var form = $('#comment');
    // console.log(form);
    form.on('submit', function(e) {
      e.preventDefault();
      // console.log("haha");
      var contents = form.serialize();      /*$('#body').val();*/
      // var contents = $("#comment_body").val();
      console.log(contents);
      $.ajax({
        url: "<%=create_comment_to_post_path%>",
        method: "POST",
        data: contents
        // data: {body: contents}
      })
      
    });
    
    var max_text_length = 50;
     $('#comment').on('keyup', function() {
       var text_length = $('#comment_body').val().length;
      
      $('#word_count').addClass('text-success').removeClass('text-danger');
      // console.log(text_length);
      if(text_length >= max_text_length) {
        alert("최대 길이 넘음");
        
        $('#word_count').addClass('text-danger').removeClass('text-sucess');
        $('#comment_body').val($('#comment_body').val().substr(0, max_text_length))
        text_length = $('#comment_body').val().length;
        
      }
       $('#word_count').text(text_length); 
     })
    
  })

  
</script>